### PR TITLE
Update BIPMapper

### PR DESCRIPTION
**Pull request by amyels**
- Faster BIPMapping heuristic and improved user control features are directly from a previously unmerged PR in terra originally authored by @gnannicini:
https://github.com/Qiskit/qiskit-terra/pull/8787 

- Merged more recent changes currently still in qiskit-terra: 
https://github.com/Qiskit/qiskit-terra/pull/9840
https://github.com/Qiskit/qiskit-terra/pull/9840

transpile, BIPMapping, and BIPMappingModel all behave as expected with various inputs

### CODE REVIEW

**Comment by gnannicini** [comment]
There is an issue with file formatting:

lint: commands[0]> black --check qiskit_bip_mapper setup.py
would reformat qiskit_bip_mapper/bip_mapping.py
would reformat qiskit_bip_mapper/bip_model.py

This is blocking the merge. Can you have a quick look at it? Running the automatic formatting tool should be enough.

**Comment by amyels** [comment]
> There is an issue with file formatting:
> 
> lint: commands[0]> black --check qiskit_bip_mapper setup.py would reformat qiskit_bip_mapper/bip_mapping.py would reformat qiskit_bip_mapper/bip_model.py
> 
> This is blocking the merge. Can you have a quick look at it? Running the automatic formatting tool should be enough.

reformatted with black, should work now!

**Comment by gnannicini** [comment]
Now these are reported as errors:

qiskit_bip_mapper/bip_mapping.py:168:9: D205 1 blank line required between summary line and description
qiskit_bip_mapper/bip_mapping.py:311:9: D205 1 blank line required between summary line and description
qiskit_bip_mapper/bip_mapping.py:311:9: D209 [*] Multi-line docstring closing quotes should be on a separate line
qiskit_bip_mapper/bip_model.py:47:9: D202 [*] No blank lines allowed after function docstring (found 1)
qiskit_bip_mapper/bip_model.py:47:9: D205 1 blank line required between summary line and description
qiskit_bip_mapper/bip_model.py:47:9: D212 [*] Multi-line docstring summary should start at the first line
qiskit_bip_mapper/bip_model.py:47:9: D415 [*] First line should end with a period, question mark, or exclamation point
qiskit_bip_mapper/bip_model.py:7[30](https://github.com/qiskit-community/qiskit-bip-mapper/actions/runs/5835408970/job/15827651935?pr=5#step:6:31):15: UP011 [*] Unnecessary parameters to `functools.lru_cache`
qiskit_bip_mapper/bip_model.py:738:15: UP011 [*] Unnecessary parameters to `functools.lru_cache`
Found 9 errors.
[*] 6 potentially fixable with the --fix option.
lint: exit 1 (0.03 seconds) /home/runner/work/qiskit-bip-mapper/qiskit-bip-mapper> ruff check qiskit_bip_mapper setup.py pid=2030
.pkg: _exit> python /opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True pbr.build
  lint: FAIL code 1 (46.89=setup[46.[41](https://github.com/qiskit-community/qiskit-bip-mapper/actions/runs/5835408970/job/15827651935?pr=5#step:6:42)]+cmd[0.45,0.03] seconds)
  evaluation failed :( (47.59 seconds)
Error: Process completed with exit code 1.

**Comment by amyels** [comment]
> Now these are reported as errors:
> 
> qiskit_bip_mapper/bip_mapping.py:168:9: D205 1 blank line required between summary line and description qiskit_bip_mapper/bip_mapping.py:311:9: D205 1 blank line required between summary line and description qiskit_bip_mapper/bip_mapping.py:311:9: D209 [_] Multi-line docstring closing quotes should be on a separate line qiskit_bip_mapper/bip_model.py:47:9: D202 [_] No blank lines allowed after function docstring (found 1) qiskit_bip_mapper/bip_model.py:47:9: D205 1 blank line required between summary line and description qiskit_bip_mapper/bip_model.py:47:9: D212 [_] Multi-line docstring summary should start at the first line qiskit_bip_mapper/bip_model.py:47:9: D415 [_] First line should end with a period, question mark, or exclamation point qiskit_bip_mapper/bip_model.py:7[30](https://github.com/qiskit-community/qiskit-bip-mapper/actions/runs/5835408970/job/15827651935?pr=5#step:6:31):15: UP011 [_] Unnecessary parameters to `functools.lru_cache` qiskit_bip_mapper/bip_model.py:738:15: UP011 [_] Unnecessary parameters to `functools.lru_cache` Found 9 errors. [*] 6 potentially fixable with the --fix option. lint: exit 1 (0.03 seconds) /home/runner/work/qiskit-bip-mapper/qiskit-bip-mapper> ruff check qiskit_bip_mapper setup.py pid=2030 .pkg: _exit> python /opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True pbr.build lint: FAIL code 1 (46.89=setup[46.[41](https://github.com/qiskit-community/qiskit-bip-mapper/actions/runs/5835408970/job/15827651935?pr=5#step:6:42)]+cmd[0.45,0.03] seconds) evaluation failed :( (47.59 seconds) Error: Process completed with exit code 1.

all issues should be fixed now

**Pull request merged**
